### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by rhari991** [nirbhayph/Blipper#1]
You probably don't want to use a real person's phone number in the screenshots.

**Comment by nirbhayph** [comment]
That's ok.. Just was updating my stuff.. I as it is don't have time to look
into that now.. Baadmein karunga.. Chu insaan

**Comment by nirbhayph** [comment]
Ok I just checked.. Those are random numbers only.. 
😉

**Comment by rhari991** [comment]
Manish's number rings.

**Comment by nirbhayph** [comment]
Ok
